/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { ShareholdersService } from './services/shareholders.service';
import { ProductsService } from './services/products.service';
import { MembersService } from './services/members.service';
import { InstallmentManagementService } from './services/installment-management.service';
import { AgentsService } from './services/agents.service';
import { WithdrawalControllerService } from './services/withdrawal-controller.service';
import { RequestProductControllerService } from './services/request-product-controller.service';
import { PaymentScheduleControllerService } from './services/payment-schedule-controller.service';
import { MainBalanceManagementService } from './services/main-balance-management.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    ShareholdersService,
    ProductsService,
    MembersService,
    InstallmentManagementService,
    AgentsService,
    WithdrawalControllerService,
    RequestProductControllerService,
    PaymentScheduleControllerService,
    MainBalanceManagementService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
