/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Agent } from './models/agent';
export type { DashboardMetricsDto } from './models/dashboard-metrics-dto';
export type { DeletedAgent } from './models/deleted-agent';
export type { DeletedMember } from './models/deleted-member';
export type { DeletedUser } from './models/deleted-user';
export type { Installment } from './models/installment';
export type { InstallmentCreateDto } from './models/installment-create-dto';
export type { InstallmentResponseDto } from './models/installment-response-dto';
export type { InstallmentUpdateDto } from './models/installment-update-dto';
export type { Member } from './models/member';
export type { PaymentSchedule } from './models/payment-schedule';
export type { PaymentScheduleRequestDto } from './models/payment-schedule-request-dto';
export type { Product } from './models/product';
export type { ProductRequestDto } from './models/product-request-dto';
export type { ProductResponseDto } from './models/product-response-dto';
export type { RequestProduct } from './models/request-product';
export type { ShareholderCreateDto } from './models/shareholder-create-dto';
export type { ShareholderDashboardDto } from './models/shareholder-dashboard-dto';
export type { ShareholderDetailsDto } from './models/shareholder-details-dto';
export type { ShareholderDto } from './models/shareholder-dto';
export type { ShareholderUpdateDto } from './models/shareholder-update-dto';
export type { User } from './models/user';
