/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Agent } from './models/agent';
export type { Installment } from './models/installment';
export type { Member } from './models/member';
export type { Product } from './models/product';
export type { RequestProduct } from './models/request-product';
export type { Shareholder } from './models/shareholder';
export type { User } from './models/user';
