/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InstallmentResponseDto } from '../../models/installment-response-dto';
import { InstallmentUpdateDto } from '../../models/installment-update-dto';

export interface UpdateInstallment$Params {
  id: number;
      body: InstallmentUpdateDto
}

export function updateInstallment(http: HttpClient, rootUrl: string, params: UpdateInstallment$Params, context?: HttpContext): Observable<StrictHttpResponse<InstallmentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateInstallment.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InstallmentResponseDto>;
    })
  );
}

updateInstallment.PATH = '/api/installments/{id}';
