/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShareholderDto } from '../../models/shareholder-dto';

export interface GetAllShareholders$Params {
}

export function getAllShareholders(http: HttpClient, rootUrl: string, params?: GetAllShareholders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShareholderDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllShareholders.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ShareholderDto>>;
    })
  );
}

getAllShareholders.PATH = '/api/shareholders';
