/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Agent } from '../../models/agent';

export interface GetAgentsByStatus$Params {
  status: string;
}

export function getAgentsByStatus(http: HttpClient, rootUrl: string, params: GetAgentsByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Agent>>> {
  const rb = new RequestBuilder(rootUrl, getAgentsByStatus.PATH, 'get');
  if (params) {
    rb.path('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Agent>>;
    })
  );
}

getAgentsByStatus.PATH = '/api/agents/status/{status}';
