/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Agent } from '../../models/agent';

export interface GetAllAgents$Params {
}

export function getAllAgents(http: HttpClient, rootUrl: string, params?: GetAllAgents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Agent>>> {
  const rb = new RequestBuilder(rootUrl, getAllAgents.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Agent>>;
    })
  );
}

getAllAgents.PATH = '/api/agents';
