/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentSchedule } from '../../models/payment-schedule';

export interface EditPayment$Params {
  scheduleId: number;
  transactionId: number;
  newAmount: number;
  agentId: number;
  notes?: string;
}

export function editPayment(http: HttpClient, rootUrl: string, params: EditPayment$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentSchedule>> {
  const rb = new RequestBuilder(rootUrl, editPayment.PATH, 'put');
  if (params) {
    rb.path('scheduleId', params.scheduleId, {});
    rb.query('transactionId', params.transactionId, {});
    rb.query('newAmount', params.newAmount, {});
    rb.query('agentId', params.agentId, {});
    rb.query('notes', params.notes, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentSchedule>;
    })
  );
}

editPayment.PATH = '/api/payment-schedules/{scheduleId}/edit-payment';
