/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentSchedule } from '../../models/payment-schedule';

export interface GetOverdueSchedules$Params {
}

export function getOverdueSchedules(http: HttpClient, rootUrl: string, params?: GetOverdueSchedules$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PaymentSchedule>>> {
  const rb = new RequestBuilder(rootUrl, getOverdueSchedules.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PaymentSchedule>>;
    })
  );
}

getOverdueSchedules.PATH = '/api/payment-schedules/overdue';
