/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentTransaction } from '../../models/payment-transaction';

export interface GetPaymentTransactions$Params {
  scheduleId: number;
}

export function getPaymentTransactions(http: HttpClient, rootUrl: string, params: GetPaymentTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PaymentTransaction>>> {
  const rb = new RequestBuilder(rootUrl, getPaymentTransactions.PATH, 'get');
  if (params) {
    rb.path('scheduleId', params.scheduleId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PaymentTransaction>>;
    })
  );
}

getPaymentTransactions.PATH = '/api/payment-schedules/{scheduleId}/transactions';
