/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentSchedule } from '../../models/payment-schedule';

export interface GetPaymentSchedules$Params {
  installmentId: number;
}

export function getPaymentSchedules(http: HttpClient, rootUrl: string, params: GetPaymentSchedules$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PaymentSchedule>>> {
  const rb = new RequestBuilder(rootUrl, getPaymentSchedules.PATH, 'get');
  if (params) {
    rb.path('installmentId', params.installmentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PaymentSchedule>>;
    })
  );
}

getPaymentSchedules.PATH = '/api/payment-schedules/installment/{installmentId}';
