/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentSchedule } from '../../models/payment-schedule';

export interface UpdatePaymentSchedule$Params {
  scheduleId: number;
      body: PaymentSchedule
}

export function updatePaymentSchedule(http: HttpClient, rootUrl: string, params: UpdatePaymentSchedule$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentSchedule>> {
  const rb = new RequestBuilder(rootUrl, updatePaymentSchedule.PATH, 'put');
  if (params) {
    rb.path('scheduleId', params.scheduleId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentSchedule>;
    })
  );
}

updatePaymentSchedule.PATH = '/api/payment-schedules/{scheduleId}';
