/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmountRequestDto } from '../../models/amount-request-dto';
import { MainBalanceResponseDto } from '../../models/main-balance-response-dto';

export interface AddInstallmentReturn$Params {
      body: AmountRequestDto
}

export function addInstallmentReturn(http: HttpClient, rootUrl: string, params: AddInstallmentReturn$Params, context?: HttpContext): Observable<StrictHttpResponse<MainBalanceResponseDto>> {
  const rb = new RequestBuilder(rootUrl, addInstallmentReturn.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MainBalanceResponseDto>;
    })
  );
}

addInstallmentReturn.PATH = '/api/main-balance/installment-return';
