/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EarningsResponseDto } from '../../models/earnings-response-dto';

export interface CalculateEarnings$Params {
}

export function calculateEarnings(http: HttpClient, rootUrl: string, params?: CalculateEarnings$Params, context?: HttpContext): Observable<StrictHttpResponse<EarningsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, calculateEarnings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EarningsResponseDto>;
    })
  );
}

calculateEarnings.PATH = '/api/main-balance/earnings';
