/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MainBalanceResponseDto } from '../../models/main-balance-response-dto';

export interface GetBalance$Params {
}

export function getBalance(http: HttpClient, rootUrl: string, params?: GetBalance$Params, context?: HttpContext): Observable<StrictHttpResponse<MainBalanceResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getBalance.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MainBalanceResponseDto>;
    })
  );
}

getBalance.PATH = '/api/main-balance';
