/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Installment } from '../../models/installment';

export interface GetInstallmentById$Params {
  id: number;
}

export function getInstallmentById(http: HttpClient, rootUrl: string, params: GetInstallmentById$Params, context?: HttpContext): Observable<StrictHttpResponse<Installment>> {
  const rb = new RequestBuilder(rootUrl, getInstallmentById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Installment>;
    })
  );
}

getInstallmentById.PATH = '/api/installments/{id}';
