/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Installment } from '../../models/installment';

export interface SearchInstallment$Params {
  keyword: string;
}

export function searchInstallment(http: HttpClient, rootUrl: string, params: SearchInstallment$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Installment>>> {
  const rb = new RequestBuilder(rootUrl, searchInstallment.PATH, 'get');
  if (params) {
    rb.query('keyword', params.keyword, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Installment>>;
    })
  );
}

searchInstallment.PATH = '/api/installments/search';
