/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Installment } from '../../models/installment';

export interface CreateInstallment$Params {
      body: Installment
}

export function createInstallment(http: HttpClient, rootUrl: string, params: CreateInstallment$Params, context?: HttpContext): Observable<StrictHttpResponse<Installment>> {
  const rb = new RequestBuilder(rootUrl, createInstallment.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Installment>;
    })
  );
}

createInstallment.PATH = '/api/installments';
