/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Agent } from '../models/agent';
import { createAgent } from '../fn/agent-controller/create-agent';
import { CreateAgent$Params } from '../fn/agent-controller/create-agent';
import { deleteAgent } from '../fn/agent-controller/delete-agent';
import { DeleteAgent$Params } from '../fn/agent-controller/delete-agent';
import { getAgentById } from '../fn/agent-controller/get-agent-by-id';
import { GetAgentById$Params } from '../fn/agent-controller/get-agent-by-id';
import { getAgentsByStatus } from '../fn/agent-controller/get-agents-by-status';
import { GetAgentsByStatus$Params } from '../fn/agent-controller/get-agents-by-status';
import { getAllAgents } from '../fn/agent-controller/get-all-agents';
import { GetAllAgents$Params } from '../fn/agent-controller/get-all-agents';
import { updateAgent } from '../fn/agent-controller/update-agent';
import { UpdateAgent$Params } from '../fn/agent-controller/update-agent';
import { updateAgentStatus } from '../fn/agent-controller/update-agent-status';
import { UpdateAgentStatus$Params } from '../fn/agent-controller/update-agent-status';

@Injectable({ providedIn: 'root' })
export class AgentControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateAgent()` */
  static readonly UpdateAgentPath = '/api/agents/updatebyid/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAgent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAgent$Response(params: UpdateAgent$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return updateAgent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAgent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAgent(params: UpdateAgent$Params, context?: HttpContext): Observable<{
}> {
    return this.updateAgent$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `updateAgentStatus()` */
  static readonly UpdateAgentStatusPath = '/api/agents/update/status/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAgentStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateAgentStatus$Response(params: UpdateAgentStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return updateAgentStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAgentStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateAgentStatus(params: UpdateAgentStatus$Params, context?: HttpContext): Observable<{
}> {
    return this.updateAgentStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `createAgent()` */
  static readonly CreateAgentPath = '/api/agents/create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createAgent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAgent$Response(params: CreateAgent$Params, context?: HttpContext): Observable<StrictHttpResponse<Agent>> {
    return createAgent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createAgent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAgent(params: CreateAgent$Params, context?: HttpContext): Observable<Agent> {
    return this.createAgent$Response(params, context).pipe(
      map((r: StrictHttpResponse<Agent>): Agent => r.body)
    );
  }

  /** Path part for operation `getAgentsByStatus()` */
  static readonly GetAgentsByStatusPath = '/api/agents/get/status/{status}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAgentsByStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAgentsByStatus$Response(params: GetAgentsByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Agent>>> {
    return getAgentsByStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAgentsByStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAgentsByStatus(params: GetAgentsByStatus$Params, context?: HttpContext): Observable<Array<Agent>> {
    return this.getAgentsByStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Agent>>): Array<Agent> => r.body)
    );
  }

  /** Path part for operation `getAgentById()` */
  static readonly GetAgentByIdPath = '/api/agents/findbyid/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAgentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAgentById$Response(params: GetAgentById$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getAgentById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAgentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAgentById(params: GetAgentById$Params, context?: HttpContext): Observable<{
}> {
    return this.getAgentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getAllAgents()` */
  static readonly GetAllAgentsPath = '/api/agents/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllAgents()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAgents$Response(params?: GetAllAgents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Agent>>> {
    return getAllAgents(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllAgents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAgents(params?: GetAllAgents$Params, context?: HttpContext): Observable<Array<Agent>> {
    return this.getAllAgents$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Agent>>): Array<Agent> => r.body)
    );
  }

  /** Path part for operation `deleteAgent()` */
  static readonly DeleteAgentPath = '/api/agents/deletebyid/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteAgent()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAgent$Response(params: DeleteAgent$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return deleteAgent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteAgent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAgent(params: DeleteAgent$Params, context?: HttpContext): Observable<{
}> {
    return this.deleteAgent$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
