/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createInstallment } from '../fn/installment-management/create-installment';
import { CreateInstallment$Params } from '../fn/installment-management/create-installment';
import { createInstallmentWithImages } from '../fn/installment-management/create-installment-with-images';
import { CreateInstallmentWithImages$Params } from '../fn/installment-management/create-installment-with-images';
import { deleteInstallment } from '../fn/installment-management/delete-installment';
import { DeleteInstallment$Params } from '../fn/installment-management/delete-installment';
import { getAllInstallments } from '../fn/installment-management/get-all-installments';
import { GetAllInstallments$Params } from '../fn/installment-management/get-all-installments';
import { getInstallmentById } from '../fn/installment-management/get-installment-by-id';
import { GetInstallmentById$Params } from '../fn/installment-management/get-installment-by-id';
import { getInstallmentImages } from '../fn/installment-management/get-installment-images';
import { GetInstallmentImages$Params } from '../fn/installment-management/get-installment-images';
import { InstallmentResponseDto } from '../models/installment-response-dto';
import { searchInstallment } from '../fn/installment-management/search-installment';
import { SearchInstallment$Params } from '../fn/installment-management/search-installment';
import { updateInstallment } from '../fn/installment-management/update-installment';
import { UpdateInstallment$Params } from '../fn/installment-management/update-installment';
import { uploadInstallmentImages } from '../fn/installment-management/upload-installment-images';
import { UploadInstallmentImages$Params } from '../fn/installment-management/upload-installment-images';


/**
 * APIs for managing installments
 */
@Injectable({ providedIn: 'root' })
export class InstallmentManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getInstallmentById()` */
  static readonly GetInstallmentByIdPath = '/api/installments/{id}';

  /**
   * Get installment by ID.
   *
   * Retrieves a specific installment by its ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInstallmentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInstallmentById$Response(params: GetInstallmentById$Params, context?: HttpContext): Observable<StrictHttpResponse<InstallmentResponseDto>> {
    return getInstallmentById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get installment by ID.
   *
   * Retrieves a specific installment by its ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInstallmentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInstallmentById(params: GetInstallmentById$Params, context?: HttpContext): Observable<InstallmentResponseDto> {
    return this.getInstallmentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<InstallmentResponseDto>): InstallmentResponseDto => r.body)
    );
  }

  /** Path part for operation `updateInstallment()` */
  static readonly UpdateInstallmentPath = '/api/installments/{id}';

  /**
   * Update installment.
   *
   * Updates an existing installment
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateInstallment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateInstallment$Response(params: UpdateInstallment$Params, context?: HttpContext): Observable<StrictHttpResponse<InstallmentResponseDto>> {
    return updateInstallment(this.http, this.rootUrl, params, context);
  }

  /**
   * Update installment.
   *
   * Updates an existing installment
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateInstallment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateInstallment(params: UpdateInstallment$Params, context?: HttpContext): Observable<InstallmentResponseDto> {
    return this.updateInstallment$Response(params, context).pipe(
      map((r: StrictHttpResponse<InstallmentResponseDto>): InstallmentResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteInstallment()` */
  static readonly DeleteInstallmentPath = '/api/installments/{id}';

  /**
   * Delete installment.
   *
   * Deletes an installment by ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteInstallment()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteInstallment$Response(params: DeleteInstallment$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return deleteInstallment(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete installment.
   *
   * Deletes an installment by ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteInstallment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteInstallment(params: DeleteInstallment$Params, context?: HttpContext): Observable<{
}> {
    return this.deleteInstallment$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getAllInstallments()` */
  static readonly GetAllInstallmentsPath = '/api/installments';

  /**
   * Get all installments.
   *
   * Retrieves all installments
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllInstallments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllInstallments$Response(params?: GetAllInstallments$Params, context?: HttpContext): Observable<StrictHttpResponse<InstallmentResponseDto>> {
    return getAllInstallments(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all installments.
   *
   * Retrieves all installments
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllInstallments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllInstallments(params?: GetAllInstallments$Params, context?: HttpContext): Observable<InstallmentResponseDto> {
    return this.getAllInstallments$Response(params, context).pipe(
      map((r: StrictHttpResponse<InstallmentResponseDto>): InstallmentResponseDto => r.body)
    );
  }

  /** Path part for operation `createInstallment()` */
  static readonly CreateInstallmentPath = '/api/installments';

  /**
   * Create new installment.
   *
   * Creates a new installment without images
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createInstallment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createInstallment$Response(params: CreateInstallment$Params, context?: HttpContext): Observable<StrictHttpResponse<InstallmentResponseDto>> {
    return createInstallment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create new installment.
   *
   * Creates a new installment without images
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createInstallment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createInstallment(params: CreateInstallment$Params, context?: HttpContext): Observable<InstallmentResponseDto> {
    return this.createInstallment$Response(params, context).pipe(
      map((r: StrictHttpResponse<InstallmentResponseDto>): InstallmentResponseDto => r.body)
    );
  }

  /** Path part for operation `getInstallmentImages()` */
  static readonly GetInstallmentImagesPath = '/api/installments/{id}/images';

  /**
   * Get installment images.
   *
   * Retrieves all image paths for an installment
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInstallmentImages()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInstallmentImages$Response(params: GetInstallmentImages$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getInstallmentImages(this.http, this.rootUrl, params, context);
  }

  /**
   * Get installment images.
   *
   * Retrieves all image paths for an installment
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInstallmentImages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInstallmentImages(params: GetInstallmentImages$Params, context?: HttpContext): Observable<{
}> {
    return this.getInstallmentImages$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `uploadInstallmentImages()` */
  static readonly UploadInstallmentImagesPath = '/api/installments/{id}/images';

  /**
   * Upload images to existing installment.
   *
   * Uploads images to an existing installment
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadInstallmentImages()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadInstallmentImages$Response(params: UploadInstallmentImages$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return uploadInstallmentImages(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload images to existing installment.
   *
   * Uploads images to an existing installment
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadInstallmentImages$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadInstallmentImages(params: UploadInstallmentImages$Params, context?: HttpContext): Observable<void> {
    return this.uploadInstallmentImages$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `createInstallmentWithImages()` */
  static readonly CreateInstallmentWithImagesPath = '/api/installments/with-images';

  /**
   * Create installment with images.
   *
   * Creates a new installment with optional images
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createInstallmentWithImages()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  createInstallmentWithImages$Response(params?: CreateInstallmentWithImages$Params, context?: HttpContext): Observable<StrictHttpResponse<InstallmentResponseDto>> {
    return createInstallmentWithImages(this.http, this.rootUrl, params, context);
  }

  /**
   * Create installment with images.
   *
   * Creates a new installment with optional images
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createInstallmentWithImages$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  createInstallmentWithImages(params?: CreateInstallmentWithImages$Params, context?: HttpContext): Observable<InstallmentResponseDto> {
    return this.createInstallmentWithImages$Response(params, context).pipe(
      map((r: StrictHttpResponse<InstallmentResponseDto>): InstallmentResponseDto => r.body)
    );
  }

  /** Path part for operation `searchInstallment()` */
  static readonly SearchInstallmentPath = '/api/installments/search';

  /**
   * Search installments.
   *
   * Search installments by member name, product name, or phone number
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchInstallment()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchInstallment$Response(params: SearchInstallment$Params, context?: HttpContext): Observable<StrictHttpResponse<InstallmentResponseDto>> {
    return searchInstallment(this.http, this.rootUrl, params, context);
  }

  /**
   * Search installments.
   *
   * Search installments by member name, product name, or phone number
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchInstallment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchInstallment(params: SearchInstallment$Params, context?: HttpContext): Observable<InstallmentResponseDto> {
    return this.searchInstallment$Response(params, context).pipe(
      map((r: StrictHttpResponse<InstallmentResponseDto>): InstallmentResponseDto => r.body)
    );
  }

}
