/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addInstallmentReturn } from '../fn/main-balance-management/add-installment-return';
import { AddInstallmentReturn$Params } from '../fn/main-balance-management/add-installment-return';
import { addInvestment } from '../fn/main-balance-management/add-investment';
import { AddInvestment$Params } from '../fn/main-balance-management/add-investment';
import { addMaintenanceCost } from '../fn/main-balance-management/add-maintenance-cost';
import { AddMaintenanceCost$Params } from '../fn/main-balance-management/add-maintenance-cost';
import { addProductCost } from '../fn/main-balance-management/add-product-cost';
import { AddProductCost$Params } from '../fn/main-balance-management/add-product-cost';
import { calculateEarnings } from '../fn/main-balance-management/calculate-earnings';
import { CalculateEarnings$Params } from '../fn/main-balance-management/calculate-earnings';
import { EarningsResponseDto } from '../models/earnings-response-dto';
import { getAllTransactions } from '../fn/main-balance-management/get-all-transactions';
import { GetAllTransactions$Params } from '../fn/main-balance-management/get-all-transactions';
import { getBalance } from '../fn/main-balance-management/get-balance';
import { GetBalance$Params } from '../fn/main-balance-management/get-balance';
import { MainBalanceResponseDto } from '../models/main-balance-response-dto';
import { TransactionHistoryResponseDto } from '../models/transaction-history-response-dto';
import { withdraw } from '../fn/main-balance-management/withdraw';
import { Withdraw$Params } from '../fn/main-balance-management/withdraw';


/**
 * APIs for managing the main balance of microcredit system
 */
@Injectable({ providedIn: 'root' })
export class MainBalanceManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `withdraw()` */
  static readonly WithdrawPath = '/api/main-balance/withdraw';

  /**
   * Withdraw funds.
   *
   * Allows investor to withdraw money from main balance
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `withdraw()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  withdraw$Response(params: Withdraw$Params, context?: HttpContext): Observable<StrictHttpResponse<MainBalanceResponseDto>> {
    return withdraw(this.http, this.rootUrl, params, context);
  }

  /**
   * Withdraw funds.
   *
   * Allows investor to withdraw money from main balance
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `withdraw$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  withdraw(params: Withdraw$Params, context?: HttpContext): Observable<MainBalanceResponseDto> {
    return this.withdraw$Response(params, context).pipe(
      map((r: StrictHttpResponse<MainBalanceResponseDto>): MainBalanceResponseDto => r.body)
    );
  }

  /** Path part for operation `addProductCost()` */
  static readonly AddProductCostPath = '/api/main-balance/product-cost';

  /**
   * Add product cost.
   *
   * Records product purchase expenses
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addProductCost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addProductCost$Response(params: AddProductCost$Params, context?: HttpContext): Observable<StrictHttpResponse<MainBalanceResponseDto>> {
    return addProductCost(this.http, this.rootUrl, params, context);
  }

  /**
   * Add product cost.
   *
   * Records product purchase expenses
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addProductCost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addProductCost(params: AddProductCost$Params, context?: HttpContext): Observable<MainBalanceResponseDto> {
    return this.addProductCost$Response(params, context).pipe(
      map((r: StrictHttpResponse<MainBalanceResponseDto>): MainBalanceResponseDto => r.body)
    );
  }

  /** Path part for operation `addMaintenanceCost()` */
  static readonly AddMaintenanceCostPath = '/api/main-balance/maintenance-cost';

  /**
   * Add maintenance cost.
   *
   * Records system maintenance expenses
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addMaintenanceCost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addMaintenanceCost$Response(params: AddMaintenanceCost$Params, context?: HttpContext): Observable<StrictHttpResponse<MainBalanceResponseDto>> {
    return addMaintenanceCost(this.http, this.rootUrl, params, context);
  }

  /**
   * Add maintenance cost.
   *
   * Records system maintenance expenses
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addMaintenanceCost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addMaintenanceCost(params: AddMaintenanceCost$Params, context?: HttpContext): Observable<MainBalanceResponseDto> {
    return this.addMaintenanceCost$Response(params, context).pipe(
      map((r: StrictHttpResponse<MainBalanceResponseDto>): MainBalanceResponseDto => r.body)
    );
  }

  /** Path part for operation `addInvestment()` */
  static readonly AddInvestmentPath = '/api/main-balance/investment';

  /**
   * Add investment.
   *
   * Adds investment from a shareholder to main balance
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addInvestment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addInvestment$Response(params: AddInvestment$Params, context?: HttpContext): Observable<StrictHttpResponse<MainBalanceResponseDto>> {
    return addInvestment(this.http, this.rootUrl, params, context);
  }

  /**
   * Add investment.
   *
   * Adds investment from a shareholder to main balance
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addInvestment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addInvestment(params: AddInvestment$Params, context?: HttpContext): Observable<MainBalanceResponseDto> {
    return this.addInvestment$Response(params, context).pipe(
      map((r: StrictHttpResponse<MainBalanceResponseDto>): MainBalanceResponseDto => r.body)
    );
  }

  /** Path part for operation `addInstallmentReturn()` */
  static readonly AddInstallmentReturnPath = '/api/main-balance/installment-return';

  /**
   * Add installment return.
   *
   * Records installment payment received from borrowers
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addInstallmentReturn()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addInstallmentReturn$Response(params: AddInstallmentReturn$Params, context?: HttpContext): Observable<StrictHttpResponse<MainBalanceResponseDto>> {
    return addInstallmentReturn(this.http, this.rootUrl, params, context);
  }

  /**
   * Add installment return.
   *
   * Records installment payment received from borrowers
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addInstallmentReturn$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addInstallmentReturn(params: AddInstallmentReturn$Params, context?: HttpContext): Observable<MainBalanceResponseDto> {
    return this.addInstallmentReturn$Response(params, context).pipe(
      map((r: StrictHttpResponse<MainBalanceResponseDto>): MainBalanceResponseDto => r.body)
    );
  }

  /** Path part for operation `getBalance()` */
  static readonly GetBalancePath = '/api/main-balance';

  /**
   * Get current main balance.
   *
   * Fetches the current main balance with all totals
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBalance()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBalance$Response(params?: GetBalance$Params, context?: HttpContext): Observable<StrictHttpResponse<MainBalanceResponseDto>> {
    return getBalance(this.http, this.rootUrl, params, context);
  }

  /**
   * Get current main balance.
   *
   * Fetches the current main balance with all totals
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBalance$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBalance(params?: GetBalance$Params, context?: HttpContext): Observable<MainBalanceResponseDto> {
    return this.getBalance$Response(params, context).pipe(
      map((r: StrictHttpResponse<MainBalanceResponseDto>): MainBalanceResponseDto => r.body)
    );
  }

  /** Path part for operation `getAllTransactions()` */
  static readonly GetAllTransactionsPath = '/api/main-balance/transactions';

  /**
   * Get all transactions.
   *
   * Fetches all transaction history records
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllTransactions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTransactions$Response(params?: GetAllTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<TransactionHistoryResponseDto>> {
    return getAllTransactions(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all transactions.
   *
   * Fetches all transaction history records
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllTransactions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTransactions(params?: GetAllTransactions$Params, context?: HttpContext): Observable<TransactionHistoryResponseDto> {
    return this.getAllTransactions$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransactionHistoryResponseDto>): TransactionHistoryResponseDto => r.body)
    );
  }

  /** Path part for operation `calculateEarnings()` */
  static readonly CalculateEarningsPath = '/api/main-balance/earnings';

  /**
   * Calculate investor earnings.
   *
   * Calculates total earnings for investors
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `calculateEarnings()` instead.
   *
   * This method doesn't expect any request body.
   */
  calculateEarnings$Response(params?: CalculateEarnings$Params, context?: HttpContext): Observable<StrictHttpResponse<EarningsResponseDto>> {
    return calculateEarnings(this.http, this.rootUrl, params, context);
  }

  /**
   * Calculate investor earnings.
   *
   * Calculates total earnings for investors
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `calculateEarnings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  calculateEarnings(params?: CalculateEarnings$Params, context?: HttpContext): Observable<EarningsResponseDto> {
    return this.calculateEarnings$Response(params, context).pipe(
      map((r: StrictHttpResponse<EarningsResponseDto>): EarningsResponseDto => r.body)
    );
  }

}
