/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deletePayment } from '../fn/payment-schedule-controller/delete-payment';
import { DeletePayment$Params } from '../fn/payment-schedule-controller/delete-payment';
import { getMonthlyInstallmentAmount } from '../fn/payment-schedule-controller/get-monthly-installment-amount';
import { GetMonthlyInstallmentAmount$Params } from '../fn/payment-schedule-controller/get-monthly-installment-amount';
import { getPaymentById } from '../fn/payment-schedule-controller/get-payment-by-id';
import { GetPaymentById$Params } from '../fn/payment-schedule-controller/get-payment-by-id';
import { getPaymentsByAgent } from '../fn/payment-schedule-controller/get-payments-by-agent';
import { GetPaymentsByAgent$Params } from '../fn/payment-schedule-controller/get-payments-by-agent';
import { getPaymentsByInstallment } from '../fn/payment-schedule-controller/get-payments-by-installment';
import { GetPaymentsByInstallment$Params } from '../fn/payment-schedule-controller/get-payments-by-installment';
import { getPaymentsByMember } from '../fn/payment-schedule-controller/get-payments-by-member';
import { GetPaymentsByMember$Params } from '../fn/payment-schedule-controller/get-payments-by-member';
import { getRemainingBalance } from '../fn/payment-schedule-controller/get-remaining-balance';
import { GetRemainingBalance$Params } from '../fn/payment-schedule-controller/get-remaining-balance';
import { payInstallment } from '../fn/payment-schedule-controller/pay-installment';
import { PayInstallment$Params } from '../fn/payment-schedule-controller/pay-installment';

@Injectable({ providedIn: 'root' })
export class PaymentScheduleControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `payInstallment()` */
  static readonly PayInstallmentPath = '/api/payment-schedules/pay';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `payInstallment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  payInstallment$Response(params: PayInstallment$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return payInstallment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `payInstallment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  payInstallment(params: PayInstallment$Params, context?: HttpContext): Observable<{
}> {
    return this.payInstallment$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getPaymentById()` */
  static readonly GetPaymentByIdPath = '/api/payment-schedules/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaymentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaymentById$Response(params: GetPaymentById$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getPaymentById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaymentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaymentById(params: GetPaymentById$Params, context?: HttpContext): Observable<{
}> {
    return this.getPaymentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `deletePayment()` */
  static readonly DeletePaymentPath = '/api/payment-schedules/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deletePayment()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePayment$Response(params: DeletePayment$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return deletePayment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deletePayment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePayment(params: DeletePayment$Params, context?: HttpContext): Observable<{
}> {
    return this.deletePayment$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getPaymentsByMember()` */
  static readonly GetPaymentsByMemberPath = '/api/payment-schedules/member/{memberId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaymentsByMember()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaymentsByMember$Response(params: GetPaymentsByMember$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getPaymentsByMember(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaymentsByMember$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaymentsByMember(params: GetPaymentsByMember$Params, context?: HttpContext): Observable<{
}> {
    return this.getPaymentsByMember$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getPaymentsByInstallment()` */
  static readonly GetPaymentsByInstallmentPath = '/api/payment-schedules/installment/{installmentId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaymentsByInstallment()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaymentsByInstallment$Response(params: GetPaymentsByInstallment$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getPaymentsByInstallment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaymentsByInstallment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaymentsByInstallment(params: GetPaymentsByInstallment$Params, context?: HttpContext): Observable<{
}> {
    return this.getPaymentsByInstallment$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getMonthlyInstallmentAmount()` */
  static readonly GetMonthlyInstallmentAmountPath = '/api/payment-schedules/installment/{installmentId}/monthly-amount';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMonthlyInstallmentAmount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMonthlyInstallmentAmount$Response(params: GetMonthlyInstallmentAmount$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getMonthlyInstallmentAmount(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMonthlyInstallmentAmount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMonthlyInstallmentAmount(params: GetMonthlyInstallmentAmount$Params, context?: HttpContext): Observable<{
}> {
    return this.getMonthlyInstallmentAmount$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getRemainingBalance()` */
  static readonly GetRemainingBalancePath = '/api/payment-schedules/installment/{installmentId}/balance';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRemainingBalance()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRemainingBalance$Response(params: GetRemainingBalance$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getRemainingBalance(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRemainingBalance$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRemainingBalance(params: GetRemainingBalance$Params, context?: HttpContext): Observable<{
}> {
    return this.getRemainingBalance$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getPaymentsByAgent()` */
  static readonly GetPaymentsByAgentPath = '/api/payment-schedules/agent/{agentId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaymentsByAgent()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaymentsByAgent$Response(params: GetPaymentsByAgent$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getPaymentsByAgent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaymentsByAgent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaymentsByAgent(params: GetPaymentsByAgent$Params, context?: HttpContext): Observable<{
}> {
    return this.getPaymentsByAgent$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
