/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createShareholder } from '../fn/shareholders/create-shareholder';
import { CreateShareholder$Params } from '../fn/shareholders/create-shareholder';
import { deleteShareholder } from '../fn/shareholders/delete-shareholder';
import { DeleteShareholder$Params } from '../fn/shareholders/delete-shareholder';
import { getActiveShareholders } from '../fn/shareholders/get-active-shareholders';
import { GetActiveShareholders$Params } from '../fn/shareholders/get-active-shareholders';
import { getAllShareholders } from '../fn/shareholders/get-all-shareholders';
import { GetAllShareholders$Params } from '../fn/shareholders/get-all-shareholders';
import { getInactiveShareholders } from '../fn/shareholders/get-inactive-shareholders';
import { GetInactiveShareholders$Params } from '../fn/shareholders/get-inactive-shareholders';
import { getShareholderByEmail } from '../fn/shareholders/get-shareholder-by-email';
import { GetShareholderByEmail$Params } from '../fn/shareholders/get-shareholder-by-email';
import { getShareholderById } from '../fn/shareholders/get-shareholder-by-id';
import { GetShareholderById$Params } from '../fn/shareholders/get-shareholder-by-id';
import { getShareholderByUserId } from '../fn/shareholders/get-shareholder-by-user-id';
import { GetShareholderByUserId$Params } from '../fn/shareholders/get-shareholder-by-user-id';
import { getShareholderDashboard } from '../fn/shareholders/get-shareholder-dashboard';
import { GetShareholderDashboard$Params } from '../fn/shareholders/get-shareholder-dashboard';
import { getShareholderDetails } from '../fn/shareholders/get-shareholder-details';
import { GetShareholderDetails$Params } from '../fn/shareholders/get-shareholder-details';
import { getShareholderStatistics } from '../fn/shareholders/get-shareholder-statistics';
import { GetShareholderStatistics$Params } from '../fn/shareholders/get-shareholder-statistics';
import { ShareholderDashboardDto } from '../models/shareholder-dashboard-dto';
import { ShareholderDetailsDto } from '../models/shareholder-details-dto';
import { ShareholderDto } from '../models/shareholder-dto';
import { updateShareholder } from '../fn/shareholders/update-shareholder';
import { UpdateShareholder$Params } from '../fn/shareholders/update-shareholder';


/**
 * Shareholder management APIs
 */
@Injectable({ providedIn: 'root' })
export class ShareholdersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getShareholderById()` */
  static readonly GetShareholderByIdPath = '/api/shareholders/{id}';

  /**
   * Get shareholder by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getShareholderById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderById$Response(params: GetShareholderById$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareholderDto>> {
    return getShareholderById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get shareholder by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getShareholderById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderById(params: GetShareholderById$Params, context?: HttpContext): Observable<ShareholderDto> {
    return this.getShareholderById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShareholderDto>): ShareholderDto => r.body)
    );
  }

  /** Path part for operation `updateShareholder()` */
  static readonly UpdateShareholderPath = '/api/shareholders/{id}';

  /**
   * Update shareholder.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateShareholder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateShareholder$Response(params: UpdateShareholder$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return updateShareholder(this.http, this.rootUrl, params, context);
  }

  /**
   * Update shareholder.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateShareholder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateShareholder(params: UpdateShareholder$Params, context?: HttpContext): Observable<{
}> {
    return this.updateShareholder$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `deleteShareholder()` */
  static readonly DeleteShareholderPath = '/api/shareholders/{id}';

  /**
   * Delete shareholder.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteShareholder()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteShareholder$Response(params: DeleteShareholder$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return deleteShareholder(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete shareholder.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteShareholder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteShareholder(params: DeleteShareholder$Params, context?: HttpContext): Observable<{
}> {
    return this.deleteShareholder$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getAllShareholders()` */
  static readonly GetAllShareholdersPath = '/api/shareholders';

  /**
   * Get all shareholders.
   *
   * Retrieve a list of all shareholders
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllShareholders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllShareholders$Response(params?: GetAllShareholders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShareholderDto>>> {
    return getAllShareholders(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all shareholders.
   *
   * Retrieve a list of all shareholders
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllShareholders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllShareholders(params?: GetAllShareholders$Params, context?: HttpContext): Observable<Array<ShareholderDto>> {
    return this.getAllShareholders$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ShareholderDto>>): Array<ShareholderDto> => r.body)
    );
  }

  /** Path part for operation `createShareholder()` */
  static readonly CreateShareholderPath = '/api/shareholders';

  /**
   * Create a new shareholder.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createShareholder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createShareholder$Response(params: CreateShareholder$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return createShareholder(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new shareholder.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createShareholder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createShareholder(params: CreateShareholder$Params, context?: HttpContext): Observable<{
}> {
    return this.createShareholder$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getShareholderDetails()` */
  static readonly GetShareholderDetailsPath = '/api/shareholders/{id}/details';

  /**
   * Get shareholder details.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getShareholderDetails()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderDetails$Response(params: GetShareholderDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareholderDetailsDto>> {
    return getShareholderDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * Get shareholder details.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getShareholderDetails$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderDetails(params: GetShareholderDetails$Params, context?: HttpContext): Observable<ShareholderDetailsDto> {
    return this.getShareholderDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShareholderDetailsDto>): ShareholderDetailsDto => r.body)
    );
  }

  /** Path part for operation `getShareholderDashboard()` */
  static readonly GetShareholderDashboardPath = '/api/shareholders/{id}/dashboard';

  /**
   * Get shareholder dashboard.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getShareholderDashboard()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderDashboard$Response(params: GetShareholderDashboard$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareholderDashboardDto>> {
    return getShareholderDashboard(this.http, this.rootUrl, params, context);
  }

  /**
   * Get shareholder dashboard.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getShareholderDashboard$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderDashboard(params: GetShareholderDashboard$Params, context?: HttpContext): Observable<ShareholderDashboardDto> {
    return this.getShareholderDashboard$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShareholderDashboardDto>): ShareholderDashboardDto => r.body)
    );
  }

  /** Path part for operation `getShareholderStatistics()` */
  static readonly GetShareholderStatisticsPath = '/api/shareholders/statistics';

  /**
   * Get shareholder statistics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getShareholderStatistics()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderStatistics$Response(params?: GetShareholderStatistics$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getShareholderStatistics(this.http, this.rootUrl, params, context);
  }

  /**
   * Get shareholder statistics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getShareholderStatistics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderStatistics(params?: GetShareholderStatistics$Params, context?: HttpContext): Observable<{
}> {
    return this.getShareholderStatistics$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getInactiveShareholders()` */
  static readonly GetInactiveShareholdersPath = '/api/shareholders/inactive';

  /**
   * Get inactive shareholders.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInactiveShareholders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInactiveShareholders$Response(params?: GetInactiveShareholders$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getInactiveShareholders(this.http, this.rootUrl, params, context);
  }

  /**
   * Get inactive shareholders.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInactiveShareholders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInactiveShareholders(params?: GetInactiveShareholders$Params, context?: HttpContext): Observable<{
}> {
    return this.getInactiveShareholders$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getShareholderByUserId()` */
  static readonly GetShareholderByUserIdPath = '/api/shareholders/by-user/{userId}';

  /**
   * Get shareholder by user ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getShareholderByUserId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderByUserId$Response(params: GetShareholderByUserId$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareholderDto>> {
    return getShareholderByUserId(this.http, this.rootUrl, params, context);
  }

  /**
   * Get shareholder by user ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getShareholderByUserId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderByUserId(params: GetShareholderByUserId$Params, context?: HttpContext): Observable<ShareholderDto> {
    return this.getShareholderByUserId$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShareholderDto>): ShareholderDto => r.body)
    );
  }

  /** Path part for operation `getShareholderByEmail()` */
  static readonly GetShareholderByEmailPath = '/api/shareholders/by-email/{email}';

  /**
   * Get shareholder by email.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getShareholderByEmail()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderByEmail$Response(params: GetShareholderByEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareholderDto>> {
    return getShareholderByEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * Get shareholder by email.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getShareholderByEmail$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShareholderByEmail(params: GetShareholderByEmail$Params, context?: HttpContext): Observable<ShareholderDto> {
    return this.getShareholderByEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShareholderDto>): ShareholderDto => r.body)
    );
  }

  /** Path part for operation `getActiveShareholders()` */
  static readonly GetActiveShareholdersPath = '/api/shareholders/active';

  /**
   * Get active shareholders.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getActiveShareholders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getActiveShareholders$Response(params?: GetActiveShareholders$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getActiveShareholders(this.http, this.rootUrl, params, context);
  }

  /**
   * Get active shareholders.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getActiveShareholders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getActiveShareholders(params?: GetActiveShareholders$Params, context?: HttpContext): Observable<{
}> {
    return this.getActiveShareholders$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
