/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Shareholder } from '../../models/shareholder';

export interface GetShareholderById$Params {
  id: number;
}

export function getShareholderById(http: HttpClient, rootUrl: string, params: GetShareholderById$Params, context?: HttpContext): Observable<StrictHttpResponse<Shareholder>> {
  const rb = new RequestBuilder(rootUrl, getShareholderById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Shareholder>;
    })
  );
}

getShareholderById.PATH = '/api/shareholders/{id}';
