/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApproveWithdrawal$Params {
  requestId: number;
  processedBy: string;
}

export function approveWithdrawal(http: HttpClient, rootUrl: string, params: ApproveWithdrawal$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, approveWithdrawal.PATH, 'post');
  if (params) {
    rb.path('requestId', params.requestId, {});
    rb.query('processedBy', params.processedBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

approveWithdrawal.PATH = '/api/withdrawals/{requestId}/approve';
