/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CalculateMonthlyEarnings$Params {
  shareholderId: number;
  totalBusinessProfit: number;
}

export function calculateMonthlyEarnings(http: HttpClient, rootUrl: string, params: CalculateMonthlyEarnings$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, calculateMonthlyEarnings.PATH, 'post');
  if (params) {
    rb.path('shareholderId', params.shareholderId, {});
    rb.query('totalBusinessProfit', params.totalBusinessProfit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

calculateMonthlyEarnings.PATH = '/api/earnings/calculate/{shareholderId}';
