/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RecalculateMonthEarnings$Params {
  month: string;
  totalBusinessProfit: number;
}

export function recalculateMonthEarnings(http: HttpClient, rootUrl: string, params: RecalculateMonthEarnings$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, recalculateMonthEarnings.PATH, 'post');
  if (params) {
    rb.query('month', params.month, {});
    rb.query('totalBusinessProfit', params.totalBusinessProfit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

recalculateMonthEarnings.PATH = '/api/earnings/recalculate';
