/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeletedMember } from '../../models/deleted-member';

export interface GetDeletedMembers$Params {
}

export function getDeletedMembers(http: HttpClient, rootUrl: string, params?: GetDeletedMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DeletedMember>>> {
  const rb = new RequestBuilder(rootUrl, getDeletedMembers.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DeletedMember>>;
    })
  );
}

getDeletedMembers.PATH = '/api/members/deleted';
