/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Installment } from '../models/installment';
export interface Product {
  addedBy?: string;
  category?: string;
  costPrice?: number;
  dateAdded?: string;
  description?: string;
  id?: number;
  installments?: Array<Installment>;
  name?: string;
  price?: number;
  status?: string;
  stock?: number;
}
