/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Member } from '../models/member';
export interface Agent {
  email?: string;
  id?: number;
  joinDate?: string;
  members?: Array<Member>;
  name?: string;
  nidCard?: string;
  nominee?: string;
  phone?: string;
  photo?: string;
  role?: string;
  status?: string;
  village?: string;
  zila?: string;
}
