/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Agent {
  email?: string;
  id?: number;
  joinDate?: string;
  name: string;
  nidCard: string;
  nominee: string;
  phone: string;
  photo?: string;
  role?: string;
  status?: string;
  village: string;
  zila: string;
}
