/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dashboard metrics DTO
 */
export interface DashboardMetricsDto {

  /**
   * Monthly average earning
   */
  monthlyAverageEarning?: number;

  /**
   * Months active
   */
  monthsActive?: number;

  /**
   * ROI percentage
   */
  roiPercentage?: number;

  /**
   * Total value
   */
  totalValue?: number;
}
