/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeletedAgent {
  deletedAt?: string;
  email?: string;
  id?: number;
  joinDate?: string;
  name?: string;
  nidCard?: string;
  nominee?: string;
  originalAgentId?: number;
  phone?: string;
  photo?: string;
  role?: string;
  status?: string;
  village?: string;
  zila?: string;
}
