/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeletedMember {
  deletedAt?: string;
  id?: number;
  joinDate?: string;
  name?: string;
  nidCardImagePath?: string;
  nidCardNumber?: string;
  nomineeName?: string;
  nomineeNidCardImagePath?: string;
  nomineeNidCardNumber?: string;
  nomineePhone?: string;
  originalMemberId?: number;
  phone?: string;
  photoPath?: string;
  status?: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';
  village?: string;
  zila?: string;
}
