/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeletedMember {
  deletedAt?: string;
  id?: number;
  joinDate?: string;
  name?: string;
  nidCard?: string;
  nominee?: string;
  originalMemberId?: number;
  phone?: string;
  photo?: string;
  village?: string;
  zila?: string;
}
