/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InstallmentCreateDto {
  advanced_paid: number;
  agentId: number;
  installmentMonths: number;
  interestRate: number;
  memberId: number;
  otherCost?: number;
  productId: number;
  status?: string;
  totalAmountOfProduct: number;
}
