/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Member } from '../models/member';
import { Product } from '../models/product';
export interface Installment {
  dueAmount?: number;
  id?: number;
  installmentMonths?: number;
  member?: Member;
  nextPaymentDate?: string;
  paidAmount?: number;
  product?: Product;
  status?: string;
  totalAmount?: number;
}
