/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Agent } from '../models/agent';
import { Member } from '../models/member';
import { Product } from '../models/product';
export interface Installment {
  advanced_paid: number;
  createdTime?: string;
  given_product_agent: Agent;
  id?: number;
  imageFilePaths?: Array<string>;
  installmentMonths: number;
  interestRate: number;
  member: Member;
  monthlyInstallmentAmount?: number;
  needPaidAmount?: number;
  otherCost: number;
  product?: Product;
  status: 'PENDING' | 'ACTIVE' | 'COMPLETED' | 'OVERDUE' | 'CANCELLED' | 'DEFAULTED';
  totalAmountOfProduct: number;
  totalAmountWithInterest?: number;
  updatedTime?: string;
}
