/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Agent } from '../models/agent';
import { Installment } from '../models/installment';
export interface Member {
  agents?: Array<Agent>;
  id?: number;
  installments?: Array<Installment>;
  joinDate?: string;
  name?: string;
  nidCard?: string;
  nominee?: string;
  phone?: string;
  photo?: string;
  village?: string;
  zila?: string;
}
