/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Agent } from '../models/agent';
import { Installment } from '../models/installment';

/**
 * Member information
 */
export interface Member {
  agents?: Array<Agent>;
  id?: number;
  installments?: Array<Installment>;
  joinDate?: string;
  name: string;
  nidCardImagePath?: string;
  nidCardNumber: string;
  nomineeName: string;
  nomineeNidCardImagePath?: string;
  nomineeNidCardNumber: string;
  nomineePhone: string;
  phone: string;
  photoPath?: string;
  status?: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';
  village: string;
  zila: string;
}
