/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Agent } from '../models/agent';
import { Installment } from '../models/installment';

/**
 * Payment schedules
 */
export interface PaymentSchedule {
  collectingAgent: Agent;
  createdTime?: string;
  id?: number;
  installment: Installment;
  notes?: string;
  paidAmount: number;
  paymentDate?: string;
  remainingAmount: number;
  status: 'PENDING' | 'PARTIALLY_PAID' | 'PAID' | 'OVERDUE' | 'CANCELLED' | 'ADJUSTED' | 'COMPLETED';
  totalAmount: number;
  updatedTime?: string;
}
