/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentScheduleRequestDto {
  agentId: number;
  amount: number;
  installmentId: number;
  notes?: string;
}
