/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Agent } from '../models/agent';
import { Installment } from '../models/installment';
import { PaymentTransaction } from '../models/payment-transaction';
export interface PaymentSchedule {
  collectingAgent: Agent;
  createdTime?: string;
  dueDate: string;
  id?: number;
  installment: Installment;
  monthlyAmount: number;
  notes?: string;
  paidAmount: number;
  paymentDate?: string;
  paymentTransactions?: Array<PaymentTransaction>;
  remainingAmount: number;
  status: 'PENDING' | 'PARTIALLY_PAID' | 'PAID' | 'OVERDUE' | 'CANCELLED' | 'ADJUSTED';
  updatedTime?: string;
}
