/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Agent } from '../models/agent';
import { PaymentSchedule } from '../models/payment-schedule';
export interface PaymentTransaction {
  amount: number;
  collectingAgent: Agent;
  createdTime?: string;
  id?: number;
  notes?: string;
  paidAmount: number;
  paymentDate: string;
  paymentSchedule: PaymentSchedule;
  paymentType?: 'PAYMENT' | 'PARTIAL_PAYMENT' | 'ADVANCE_PAYMENT' | 'REFUND' | 'ADJUSTMENT' | 'PENALTY' | 'DISCOUNT';
  updatedTime?: string;
}
