/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponseDto {
  category?: string;
  costPrice?: number;
  dateAdded?: string;
  description?: string;
  id?: number;
  imageFilePaths?: Array<string>;
  isDeliveryRequired?: boolean;
  name?: string;
  price?: number;
  soldByAgentName?: string;
  totalPrice?: number;
  whoRequestId?: number;
  whoRequestName?: string;
  whoRequestNidCardNumber?: string;
  whoRequestPhone?: string;
  whoRequestVillage?: string;
  whoRequestZila?: string;
}
