/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductRequestDto {
  category?: string;
  costPrice?: number;
  description?: string;
  isDeliveryRequired?: boolean;
  name?: string;
  price?: number;
  soldByAgentId?: number;
  whoRequestId?: number;
}
