/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Agent } from '../models/agent';
import { Installment } from '../models/installment';
import { Member } from '../models/member';
export interface Product {
  category?: string;
  costPrice?: number;
  dateAdded?: string;
  description?: string;
  id?: number;
  imageFilePaths?: Array<string>;
  installment?: Installment;
  isDeliveryRequired?: boolean;
  name?: string;
  price?: number;
  soldByAgent?: Agent;
  totalPrice?: number;
  whoRequest?: Member;
}
