/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Agent } from '../models/agent';
import { Installment } from '../models/installment';
export interface Product {
  addedBy?: string;
  category?: string;
  costPrice?: number;
  dateAdded?: string;
  description?: string;
  id?: number;
  imageFilePaths?: Array<string>;
  installments?: Array<Installment>;
  isDeliveryRequired?: boolean;
  name?: string;
  price?: number;
  soldByAgent?: Agent;
  status?: string;
  stock?: number;
}
