/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Agent } from '../models/agent';
import { Member } from '../models/member';
export interface RequestProduct {
  agent?: Agent;
  approvedBy?: string;
  id?: number;
  member?: Member;
  productName?: string;
  quantity?: number;
  requestDate?: string;
  status?: string;
}
