/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DashboardMetricsDto } from '../models/dashboard-metrics-dto';
import { ShareholderDto } from '../models/shareholder-dto';

/**
 * Shareholder dashboard DTO
 */
export interface ShareholderDashboardDto {
  basicInfo?: ShareholderDto;
  performanceMetrics?: DashboardMetricsDto;
}
