/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Shareholder creation DTO
 */
export interface ShareholderCreateDto {

  /**
   * Email address
   */
  email: string;

  /**
   * House address
   */
  house?: string;

  /**
   * Total investment amount
   */
  investment?: number;

  /**
   * Join date
   */
  joinDate?: string;

  /**
   * Shareholder full name
   */
  name: string;

  /**
   * National ID card number
   */
  nidCard?: string;

  /**
   * Nominee name
   */
  nominee?: string;

  /**
   * Phone number
   */
  phone?: string;

  /**
   * Role in organization
   */
  role?: string;

  /**
   * Status
   */
  status?: 'Active' | 'Inactive';

  /**
   * District
   */
  zila?: string;
}
