/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Shareholder {
  currentBalance?: number;
  house?: string;
  id?: number;
  investment?: number;
  joinDate?: string;
  name?: string;
  nidCard?: string;
  nominee?: string;
  phone?: string;
  role?: string;
  status?: string;
  totalEarning?: number;
  totalShare?: number;
  zila?: string;
}
