/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Shareholder Data Transfer Object
 */
export interface ShareholderDto {

  /**
   * Current balance
   */
  currentBalance?: number;

  /**
   * Email address
   */
  email: string;

  /**
   * House address
   */
  house?: string;

  /**
   * Shareholder ID
   */
  id?: number;

  /**
   * Total investment amount
   */
  investment?: number;

  /**
   * Join date
   */
  joinDate?: string;

  /**
   * Shareholder full name
   */
  name: string;

  /**
   * National ID card number
   */
  nidCard?: string;

  /**
   * Nominee name
   */
  nominee?: string;

  /**
   * Phone number
   */
  phone?: string;

  /**
   * Return on Investment percentage
   */
  roi?: number;

  /**
   * Role in organization
   */
  role?: string;

  /**
   * Status
   */
  status?: 'Active' | 'Inactive';

  /**
   * Total earnings
   */
  totalEarning?: number;

  /**
   * Total number of shares
   */
  totalShare?: number;

  /**
   * Total value (investment + earnings)
   */
  totalValue?: number;

  /**
   * District
   */
  zila?: string;
}
