/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionHistoryResponseDto {
  amount?: number;
  description?: string;
  id?: number;
  shareholderId?: number;
  shareholderName?: string;
  timestamp?: string;
  type?: string;
}
