/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserDto {
  firstname?: string;
  lastname?: string;
  password?: string;
  referenceId?: number;
  role?: string;
  status?: string;
  username?: string;
}
