/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  id?: number;
  password?: string;
  referenceId?: number;
  role?: 'ADMIN' | 'AGENT' | 'SHAREHOLDER';
  status?: string;
  username?: string;
}
