/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  createdDate?: string;
  firstname?: string;
  id?: number;
  lastModifiedDate?: string;
  lastname?: string;
  referenceId?: number;
  role?: string;
  status?: string;
  username?: string;
}
